deploy:
  provider: heroku
  api_key:
    secure: G71ge2ttfm4QV3skTesUa1gktRyKmcU0eXgnZPSw72cybWJYdRp+cC8sG6x4Cl8dIJK2QOnOeSIV4KPnbURL/RCIK57PJoaL40Hgr6PyoPSmWv6v5/9AiXQ3gywAg5089wZzoT/5VgquIYmFgZ9Ae7UGmC9sHw5+1+/OomZdlu8/YPCLwIoP2acnzU7xKw1uFqlB5UUzOUFO2NZSDLlnbUOf0jgCmzuMdjXbsZY5JSFb/femw0PNV8C908HSl2I3rAhpwqcjooIQIpEP7+FG3qj/ipvAWz1kyNEB42kuthsdnGmPHSO2jSwI166vlss4kHDzaNzAYiIjGKACKfYbV+Fkx1ZltxpLFYkGaGFJsvUc2eFAB17v8O32vMuw0PM7sZYQjDlaeiSxbvLEoTLRB2Q/tAIJV5BvvpkKRbltySm2aCFFusriXbNtDOVKarWFj2nSSPyclqTldxuydtV+JziO7R9oxBioXHzdL80AXisCxOKeDAaauOQgXGMe0065eFh/ddhbRPyYl/IQcLUkX0jdXwdK2QtUp4HHSv7Vms/hBKZQC3lg7xhMfHxUnuyTJxIfP0rCQwgL8FyjEQUp7Oi0iVFrjf2aUrfQ2/+ZQ/1F52ykrsDhBumiv3zsNIy5FMTOOiFoLNlYd1Ma7S7mvw/ATRIkUvW6PnXJ46hKk8Y=
  app: buy-local-art
  on:
    repo: emilycritter/tiy-final-project
    branch: travis-issues
  run:
    - "rake db:migrate"
