language: ruby
rvm:
- 2.3.0
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: oOy9fqpkGVagaWpvlBZBy1XYlC6UnPt4fD7PM792ACPhPKnZKOw1OECunuhQephTs0ShCu0naOwaPjvszrtyW4YUElR+82D43Dv6Q213b8FNjDFHOeMnZSFB241XriWEX7dftFLoVVdecVmJMlcz5G2RGFLK2/CoglBvZBBxZRXtf/l5W3+1PsN/ZbgYVr7kMXNpG499ypyYBFlHJ4q3hxUpBkb6gq7MpONvAdc61ZrqjHQQJSx5437ehOtLme9RtEkVY/qPm1EeicRUkJpB4IJfsURmj+66Hh8zzUpI0bn3q2k43p/nD6aMQGIsl32Q5FcqOgifx42czWuU31a8fyDMP7H3NqtuNAfMfK9YpaY6Pof+8FX22z+1yqSDxY256mGuCGPVnSTXGt68GrlsOQIVHdo8MPUBO6awsImF/QBlLD/ipgz93jfyEHCQZJgd/PRE7j7N3Je8GY+fu0hPm835CQ6cK87eO1SwpGkypzILJZ0R+u3hbEvvRP0nGwcX10Y9Wfb3PSiSk8NjdsOMQr2OPkd+GV33jYMY7qfxu7O2n5lY9VGrOLyC/8SsmuEv/B+jy8cfMl2fjRywl4Lfg7Td3xJaWNJR4pJHTtLfDPQrWvbvn0sDqQ4e4pL68jqEkaf8TwiYh0annZL1g+XGzHhSTrmQdmXkB9xWHb18syc=
  app: where-art-thou
  on:
    repo: emilycritter/tiy-final-project
